title: ChenShenghan(DecemberCat)
page-top-title: ChenShenghan
top-section-bg-text: 十二月的寒冬阻挡不了春天的脚步，十二点的黑夜遮蔽不住黎明的曙光
home-subtitle: ChenShenghan&ensp;|&ensp;十二月的猫
copyright-text: '&copy; Yourname 2023-2025. All Rights Reserved.'
