title: ChenShenghan(DecemberCat)
page-top-title: ChenShenghan
top-section-bg-text: Not even the bitterest winter in December can prevent the arrival of spring, nor can the deepest night obscure the promise of the dawn
home-subtitle: ChenShenghan&ensp;|&ensp;CatOfDecember
copyright-text: '&copy; ChenShenghan 2023-2026. All Rights Reserved.'
