title: CatOfDecember
page-top-title: ChenShenghan
top-section-bg-text: Winter cannot hold back spring
home-subtitle: CatOfDecember
copyright-text: '&copy; ChenShenghan 2023-2026. All Rights Reserved.'
